# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmPesqVeiculos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPesqVeiculos(object):
    def setupUi(self, frmPesqVeiculos):
        frmPesqVeiculos.setObjectName("frmPesqVeiculos")
        frmPesqVeiculos.resize(820, 504)
        self.gridVeiculos = QtWidgets.QTableWidget(frmPesqVeiculos)
        self.gridVeiculos.setGeometry(QtCore.QRect(0, 150, 811, 291))
        self.gridVeiculos.setObjectName("gridVeiculos")
        self.gridVeiculos.setColumnCount(7)
        self.gridVeiculos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.gridVeiculos.setHorizontalHeaderItem(6, item)
        self.edtPesquisa = QtWidgets.QLineEdit(frmPesqVeiculos)
        self.edtPesquisa.setGeometry(QtCore.QRect(190, 60, 621, 20))
        self.edtPesquisa.setObjectName("edtPesquisa")
        self.cbPesquisa = QtWidgets.QComboBox(frmPesqVeiculos)
        self.cbPesquisa.setGeometry(QtCore.QRect(20, 60, 161, 22))
        self.cbPesquisa.setObjectName("cbPesquisa")
        self.cbPesquisa.addItem("")
        self.cbPesquisa.addItem("")
        self.cbPesquisa.addItem("")
        self.cbPesquisa.addItem("")
        self.cbPesquisa.addItem("")
        self.label = QtWidgets.QLabel(frmPesqVeiculos)
        self.label.setGeometry(QtCore.QRect(20, 30, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnPesquisar = QtWidgets.QPushButton(frmPesqVeiculos)
        self.btnPesquisar.setGeometry(QtCore.QRect(700, 90, 111, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../TesteProjeto/Imagens/Lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisar.setIcon(icon)
        self.btnPesquisar.setIconSize(QtCore.QSize(30, 30))
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.lblTotal = QtWidgets.QLabel(frmPesqVeiculos)
        self.lblTotal.setGeometry(QtCore.QRect(20, 450, 111, 16))
        self.lblTotal.setObjectName("lblTotal")
        self.btnExcluir = QtWidgets.QPushButton(frmPesqVeiculos)
        self.btnExcluir.setGeometry(QtCore.QRect(720, 450, 91, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../TesteProjeto/Imagens/delete-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExcluir.setIcon(icon1)
        self.btnExcluir.setIconSize(QtCore.QSize(30, 30))
        self.btnExcluir.setObjectName("btnExcluir")
        self.btnAlterar = QtWidgets.QPushButton(frmPesqVeiculos)
        self.btnAlterar.setGeometry(QtCore.QRect(610, 450, 101, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../TesteProjeto/Imagens/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlterar.setIcon(icon2)
        self.btnAlterar.setIconSize(QtCore.QSize(35, 35))
        self.btnAlterar.setObjectName("btnAlterar")

        self.retranslateUi(frmPesqVeiculos)
        QtCore.QMetaObject.connectSlotsByName(frmPesqVeiculos)

    def retranslateUi(self, frmPesqVeiculos):
        _translate = QtCore.QCoreApplication.translate
        frmPesqVeiculos.setWindowTitle(_translate("frmPesqVeiculos", "Lista de Cliente"))
        item = self.gridVeiculos.horizontalHeaderItem(0)
        item.setText(_translate("frmPesqVeiculos", "Código"))
        item = self.gridVeiculos.horizontalHeaderItem(1)
        item.setText(_translate("frmPesqVeiculos", "Marca"))
        item = self.gridVeiculos.horizontalHeaderItem(2)
        item.setText(_translate("frmPesqVeiculos", "Ano"))
        item = self.gridVeiculos.horizontalHeaderItem(3)
        item.setText(_translate("frmPesqVeiculos", "Placa"))
        item = self.gridVeiculos.horizontalHeaderItem(4)
        item.setText(_translate("frmPesqVeiculos", "Alugado"))
        item = self.gridVeiculos.horizontalHeaderItem(5)
        item.setText(_translate("frmPesqVeiculos", "Valor da Diária"))
        item = self.gridVeiculos.horizontalHeaderItem(6)
        item.setText(_translate("frmPesqVeiculos", "Tipo do Veículo"))
        self.cbPesquisa.setItemText(0, _translate("frmPesqVeiculos", "Código"))
        self.cbPesquisa.setItemText(1, _translate("frmPesqVeiculos", "Marca"))
        self.cbPesquisa.setItemText(2, _translate("frmPesqVeiculos", "Modelo"))
        self.cbPesquisa.setItemText(3, _translate("frmPesqVeiculos", "Disponível"))
        self.cbPesquisa.setItemText(4, _translate("frmPesqVeiculos", "Alugado"))
        self.label.setText(_translate("frmPesqVeiculos", "Selecione o Tipo de Pesquisa:"))
        self.btnPesquisar.setText(_translate("frmPesqVeiculos", "Pesquisar"))
        self.lblTotal.setText(_translate("frmPesqVeiculos", "TextLabel"))
        self.btnExcluir.setText(_translate("frmPesqVeiculos", "Excluir"))
        self.btnAlterar.setText(_translate("frmPesqVeiculos", "Alterar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmPesqVeiculos = QtWidgets.QDialog()
    ui = Ui_frmPesqVeiculos()
    ui.setupUi(frmPesqVeiculos)
    frmPesqVeiculos.show()
    sys.exit(app.exec_())
